// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CompilePreview(arg1) {
  return window['go']['main']['App']['CompilePreview'](arg1);
}

export function LoadLayout(arg1) {
  return window['go']['main']['App']['LoadLayout'](arg1);
}

export function LoadWorkspace(arg1) {
  return window['go']['main']['App']['LoadWorkspace'](arg1);
}

export function OpenWorkspace() {
  return window['go']['main']['App']['OpenWorkspace']();
}

export function ReadSourceFile(arg1) {
  return window['go']['main']['App']['ReadSourceFile'](arg1);
}

export function SampleCompiledFrame(arg1) {
  return window['go']['main']['App']['SampleCompiledFrame'](arg1);
}

export function SaveSourceFile(arg1) {
  return window['go']['main']['App']['SaveSourceFile'](arg1);
}

export function SelectLayoutFile() {
  return window['go']['main']['App']['SelectLayoutFile']();
}
