// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function CompilePreview(arg1:main.CompileRequest):Promise<main.CompileResponse>;

export function LoadLayout(arg1:string):Promise<main.LayoutData>;

export function LoadWorkspace(arg1:string):Promise<main.WorkspaceData>;

export function OpenWorkspace():Promise<main.WorkspaceData>;

export function ReadSourceFile(arg1:string):Promise<string>;

export function SampleCompiledFrame(arg1:main.SampleRequest):Promise<main.SampleResponse>;

export function SaveSourceFile(arg1:main.SaveSourceRequest):Promise<void>;

export function SelectLayoutFile():Promise<string>;
