package sema

const (
	ErrEffectExportedFunction      = "E001"
	ErrEffectMissingSample         = "E002"
	ErrEffectInvalidSampleArity    = "E003"
	ErrLibraryHasSample            = "E004"
	ErrLibraryHasPresets           = "E005"
	ErrDuplicateParamName          = "E010"
	ErrDuplicateFunctionName       = "E011"
	ErrDuplicateImportAlias        = "E012"
	ErrDuplicateLocalName          = "E020"
	ErrInvalidAssignmentTarget     = "E021"
	ErrUndefinedIdentifier         = "E030"
	ErrParamsAccessWithoutBlock    = "E031"
	ErrUnknownParameter            = "E032"
	ErrImportMissingExportedFunc   = "E033"
	ErrRecursionDetected           = "E040"
	ErrParamMinGreaterThanMax      = "E050"
	ErrNumericParamDefaultType     = "E051"
	ErrParamDefaultBelowMin        = "E052"
	ErrParamDefaultAboveMax        = "E053"
	ErrEnumDefaultNotString        = "E054"
	ErrEnumDefaultNotInValues      = "E055"
	ErrPresetStartOutOfRange       = "E060"
	ErrPresetFinishOutOfRange      = "E061"
	ErrPresetStartAfterLoopStart   = "E062"
	ErrPresetLoopStartAfterLoopEnd = "E063"
	ErrPresetLoopEndAfterFinish    = "E064"
	ErrPresetStartAfterFinish      = "E065"
)
